final List<String> testComments = [
  'Low quality',
  'Insecure pose',
  'Wrong category',
  'Distracting background',
  'Sunglasses hide face',
  'Can\'t see face',
  'Too dark',
  'Too bright',
  'Not fit',
  'Lacks grooming',
  'Would not date',
  'Bad angle',
  'Seems bored',
  'Posing too much',
  'Bad posture',
  'Seems stressed',
  'Looks sad',
  'Looks aggressive',
  'Looks insecure',
  'Looks upset',
  'Too dominant',
  'Unprofessional',
  'Overedited',
  'Unnatural',
  'Too staged',
  'Wrong lighting',
  'Blurred',
  'Out of focus',
  'Unflattering angle',
  'Unusual facial expression',
  'Too much make-up',
  'Too much skin',
  'Bad style',
  'Too close',
  'Too far away',
  'Too nerdy',
  'Too serious',
  'Fingernails ungroomed',
  'Arrogant',
  'Hair doesn\'t fit',
  'Unfriendly expression',
];
